### ISSUE TITLE
Possibility to save in Redis

### ISSUE THREAD

**Issue by akincansenol** [pressjitsu/wpdb-phpsessions#3]
Is there a way to sessions save to redis instead of mysql?

Akın

**Comment by soulseekah** [comment]
Not with this plugin, no. This plugin is specifically for MySQL-backed sessions.

Try https://www.digitalocean.com/community/tutorials/how-to-set-up-a-redis-server-as-a-session-handler-for-php-on-ubuntu-14-04 or some of the other redis backend plugins out there (Google "php session redis handler").

Hope this helps. Good luck.
